### ISSUE TITLE
Restaurant demo is broken

### ISSUE THREAD

**Issue by noelutz** [PolymerLabs/arcs-cdn#16]
- Back doesn't work -- navigation.
- another problem with the restaurant demo is that upon reloading, it always adds 20 restaurants to the restaurant list.

**Comment by noelutz** [comment]
Restaurant demo back button triggers the following exception: "Slot master cannot provide multiple annotation:84b5f4aabd4936c5ce51223281761ca0de53e087 inner slots"

**Comment by noelutz** [comment]
This is a storage bug. For some reason the restaurant list is imported multiple times leading to ID collisions and two slot subids being identical.

**Comment by noelutz** [comment]
Master detail is fixed (change submitted to the arc-stories). Storage issue remains for now.

**Comment by noelutz** [comment]
Introduced #nosync to fix the multiple restaurant list issue. Full discussion about why we went down that route is on Slack.

**Comment by noelutz** [comment]
Still broken parts:
 - Once you selected a favorite food + reload it gets lost
 - Variables aren't synced
 - Adding a profile Arc requires reload as well

**Comment by noelutz** [comment]
Once you selected a favorite food + reload it gets lost: **CTRL+S fixes it** => likely a race

**Comment by sjmiles** [comment]
There are a series of asynchronous signals (context changes, slot changes, user changes) that app-shell must collate to make decisions about re-planning. For the next refactor I endeavor to create a sane architecture around this (roughly corresponding to the invalidation mechanism that is there now). 

In e095448 I made sure the `applySuggestion` is asynchronous, and added a simple timeout delay as a stand-in for proper signaling.

I believe the timeout will be effective for now, since the missed slot-changes are generally very short-term (the existing asynchrony stems from the batching system the DOM renderer is using). This is a stopgap because instead of removing the race-condition, I hobbled one of the racers.

Please test against the Restaurant/Reservation demo, these changes fixed the obvious problem on my setups.

**Comment by noelutz** [comment]
- Once you selected a favorite food + reload it gets lost
Fixed. 
- Variables aren't synced
Fixed.
- Adding a profile Arc requires reload as well
Fixed.

Scott, looks like you fixed the last remaining issue. I'm going to flag this as fixed.
