### ISSUE TITLE
Icons don't show up in Gifts shopping demo

### ISSUE THREAD

**Issue by mariakleiner** [PolymerLabs/arcs-cdn#24]
https://polymerlabs.github.io/arcs-cdn/dev/apps/web/?nokey&solo=https://mmandlis.github.io/arcs-stories/0.2/arc.manifest

**Comment by sjmiles** [comment]
The problem is in the JSON data that describes the products. The asset paths should look like `assets/products/foo.png` but instead they are `../assets/products/foo.png` (extra `..`).

Currently your manifest is tapping the files at `sjmiles.github.io/arc-stories/artifacts/Products/*`. It's fine for now to use data from `sjmiles.github.io` but you should stick to the `0.2` versioned artifacts (the other ones are only for backward compat).

In other words, `sjmiles.github.io/arc-stories/0.2/Products/data/products.json` instead of `sjmiles.github.io/arc-stories/artifacts/Products/products.json`. The newer JSON files had the same bad asset paths in them, but I've just updated them.

Note that where exactly that JSON should live is an open question. 

Since you have `mmandlis.github.io/arc-stories`, consider making that the _owner_ of the Products demo. That would mean putting the JSON files and any special demo-oriented recipes or artifacts into `mmandlis.github.io/arcs-stores/0.2/[some name]` (where [some name] could be Products or ProductsDemo or whatever you want). Then we can erase whatever stale content is in `sjmiles.github.io/arc-stories/0.2/Products` (maybe all of it).

The above is just one idea, there are many ways to organize this material.

**Comment by mariakleiner** [comment]
Added JSON files to mmandlis/arcs-stories repo, here is a demo that doesn't use any sjmiles/arc-stories files:
https://polymerlabs.github.io/arcs-cdn/dev/apps/web/?nokey=&solo=https://mmandlis.github.io/arcs-stories/0.2/arc.manifest
(it almost works, except the Chooser fix (https://github.com/PolymerLabs/arcs-cdn/pull/29) that is still in review.

I'm not sure i can safely remove products artifacts from sjmiles/arc-stories repo though, I'm seeing some manifests that do reference them.
